# Tutorial de Pytorch 1: Tensores


https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

## ¿Qué es PyTorch?

Es un paquete informático científico basado en Python para ofrecer:

- Un reemplazo de NumPy para usar la potencia de las GPU.
- Una plataforma de investigación de aprendizaje profundo (*Deep Learning*) que proporciona la máxima flexibilidad y velocidad.

### Tensores

Los **tensores** son similares a los *ndarrays* de NumPy, con el añadido de que los tensores también se pueden usar en una GPU para acelerar la computación.

In [1]:
import torch

x = torch.empty(5, 3)
print(x)

tensor([[9.9184e-39, 1.0561e-38, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 4.6838e-39],
        [8.4489e-39, 9.6429e-39, 8.4490e-39],
        [9.6429e-39, 9.2755e-39, 1.0286e-38],
        [9.0919e-39, 8.9082e-39, 9.2755e-39]])


Hemos declarado una matriz vacía (no inicializada), por tanto, no contiene valores conocidos antes de su uso. Cuando se crea una matriz no inicializada, los valores que estaban en la memoria asignada en ese momento aparecerán como valores iniciales.

In [2]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0063, 0.3046, 0.7965],
        [0.3336, 0.2921, 0.4931],
        [0.0380, 0.6064, 0.1145],
        [0.1354, 0.5938, 0.5662],
        [0.7659, 0.0191, 0.0275]])


A diferencia de <code>torch.empty</code>, <code>torch.rand</code> genera unos valores aleatorios entre 0 y 1.

Podemos crear un tensor con todos los valores a cero.

In [3]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


También podemos crear un tensor a partir de una lista.

In [4]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


O crear un tensor basado en un tensor existente. Estos métodos reutilizarán propiedades del tensor de entrada, p. ej. dtype, a menos que el usuario proporcione nuevos valores.

In [5]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)    

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.7828, -0.6446,  0.0941],
        [-0.3043, -1.5295,  1.6169],
        [-0.4094,  1.6890,  1.0135],
        [-1.1487, -1.0286, -0.3093],
        [ 0.7408,  1.4012,  0.7433]])


### Operaciones

Hay varias sintaxis para las operaciones. En el siguiente ejemplo, veremos la operación de suma.

In [6]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.1437, -0.4753,  1.0807],
        [ 0.2530, -0.8880,  2.6150],
        [-0.3058,  1.7675,  1.3653],
        [-1.1100, -0.1143,  0.1803],
        [ 1.0973,  1.4709,  1.3769]])


In [7]:
print(torch.add(x, y))

tensor([[-0.1437, -0.4753,  1.0807],
        [ 0.2530, -0.8880,  2.6150],
        [-0.3058,  1.7675,  1.3653],
        [-1.1100, -0.1143,  0.1803],
        [ 1.0973,  1.4709,  1.3769]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.9265, -1.1198,  1.1749],
        [-0.0512, -2.4175,  4.2319],
        [-0.7152,  3.4565,  2.3788],
        [-2.2587, -1.1428, -0.1291],
        [ 1.8381,  2.8721,  2.1202]])


#### *in_place*

Suma *in_place*. Cuando encontramos el sufijo "_" en cualquier método correspondiente a una operación de un objeto, significa que el resultado de la operación es almacenado en el propio objeto, reemplazando al valor anterior.

In [9]:
y.add_(x)
print(y)

tensor([[-0.1437, -0.4753,  1.0807],
        [ 0.2530, -0.8880,  2.6150],
        [-0.3058,  1.7675,  1.3653],
        [-1.1100, -0.1143,  0.1803],
        [ 1.0973,  1.4709,  1.3769]])


Podemos utilizar la indexación de tensores de la misma forma que la usamos en arrays de tipo NumPy.

In [11]:
print(x[:, 1])

tensor([-0.6446, -1.5295,  1.6890, -1.0286,  1.4012])


### Reshape

Si necesitamos cambiar la "forma" de un tensor, podemos usar <code>torch.view</code>.

In [34]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print("x size: ", x.size())
print("y size: ", y.size())
print("z size: ", z.size())

x size:  torch.Size([4, 4])
y size:  torch.Size([16])
z size:  torch.Size([2, 8])


Si tenemos un tensor de un solo elemento, usamos <code>.item()</code> para obtener el valor como un número de Python.

In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.7832])
-0.7831534743309021


### Convirtiendo arrays de Numpy a tensores de PyTorch y viceversa

El tensor de PyTorch y la matriz de NumPy comparten las mismas ubicaciones de memoria subyacentes cuando el tensor está en CPU (recordemos que PyTorch puede ejecutarse tanto en CPU o GPU). Así que, si modificamos los valores del array modificaremos los valores del tensor.

In [18]:
a = torch.ones(5)
print(a)

b = a.numpy()  # Creamos un array de numpy desde un tensor de pytorch
print(b)

a.add_(1)
print("Tensor pytorch: ", a)
print("Array numpy: ", b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
Tensor pytorch:  tensor([2., 2., 2., 2., 2.])
Array numpy:  [2. 2. 2. 2. 2.]


In [19]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a) # Creamos un tensor de pytorch desde un array de numpy

np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### Tensores CUDA

Podemos mover tensores a cualquier dispositivo (GPU) mediante el método <code>.to</code>

In [20]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU

if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([0.2168], device='cuda:0')
tensor([0.2168], dtype=torch.float64)
